### ISSUE TITLE
Recipes not showing in NEI

### ISSUE THREAD

**Issue by InkDragon** [CyanideX/Subsistence#102]
Recipes for many items of the mods items are not showing in NEI. EG not showing the recipe for the barrels

**Comment by CyanideX** [comment]
As this mod was specifically designed for use with Infernal Skies, the majority of the recipes had been done using CustomThings/MineTweaker. The recipes are actually incomplete. But if you play the pack, barrels do show up in NEI. A lot of the item recipes won't show up but that is intentional.

We will most likely add configurable recipes later or remove them entirely. It's meant to be completely customizable.
